import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { summariesService } from '../services/summaries';
import { Pagination } from '../components/Pagination';

export const WeeklySummariesPage: React.FC = () => {
  const [offset, setOffset] = useState(0);
  const limit = 12;
  const { data, isLoading, isError } = useQuery({
    queryKey: ['summaries', 'weekly', offset],
    queryFn: () => summariesService.listWeekly(limit, offset),
  });

  return (
    <div className="w-full px-8 py-8">
      <header className="mb-6">
        <h1 className="text-3xl font-bold text-white">Weekly Summaries</h1>
        <p className="mt-1 text-slate-400">Phase 1 weekly snapshot generated by backend jobs.</p>
      </header>

      {isLoading ? (
        <div className="text-slate-400">Loading weekly summaries...</div>
      ) : isError ? (
        <div className="rounded-xl border border-rose-800 bg-rose-950/30 p-6 text-rose-300">
          Failed to load weekly summaries. Please try again.
        </div>
      ) : data?.items?.length ? (
        <>
          <div className="space-y-3">
            {data.items.map((item) => (
              <article key={item.public_id} className="rounded-xl border border-slate-800 bg-slate-800/30 p-4">
                <h2 className="font-semibold text-white">
                  Week of {
                    !Number.isNaN(new Date(`${item.week_start}T00:00:00Z`).getTime())
                      ? new Date(`${item.week_start}T00:00:00Z`).toLocaleDateString(undefined, { dateStyle: 'medium', timeZone: 'UTC' })
                      : 'N/A'
                  }
                </h2>
                <p className="text-xs text-slate-500">
                  Generated {
                    !Number.isNaN(new Date(item.generated_at).getTime())
                      ? new Date(item.generated_at).toLocaleString()
                      : 'N/A'
                  }
                </p>
                <div className="mt-3 grid gap-2 md:grid-cols-3">
                  <JsonBox title="Todo" value={item.todo_summary} />
                  <JsonBox title="Spending" value={item.spending_summary} />
                  <JsonBox title="Investing" value={item.investing_summary} />
                </div>
              </article>
            ))}
          </div>
          <div className="mt-4">
            <Pagination total={data.total} limit={data.limit} offset={data.offset} onPageChange={setOffset} />
          </div>
        </>
      ) : (
        <div className="rounded-xl border border-slate-800 bg-slate-800/30 p-6 text-slate-400">No weekly summaries yet.</div>
      )}
    </div>
  );
};

const JsonBox = ({ title, value }: { title: string; value: Record<string, unknown> }) => (
  <div className="rounded-lg border border-slate-700 bg-slate-900/40 p-3">
    <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{title}</p>
    <pre className="mt-2 overflow-auto text-xs text-slate-200">{JSON.stringify(value, null, 2)}</pre>
  </div>
);
