import React, { useEffect, useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays } from 'lucide-react';
import { summariesService } from '../services/summaries';
import { queryKeys } from '../lib/queryKeys';
import { PageHero } from '../components/layout/PageHero';
import { PageShell } from '../components/layout/PageShell';
import { Pagination } from '../components/Pagination';
import { SkeletonList, EmptyState, ErrorBanner } from '../components/ui/FeedbackStates';
import { formatCurrency, toNumber } from '../utils/numberFormat';
import { formatDate, formatDateTime } from '../utils/dateFormat';
import type { WeeklySummary } from '../services/summaries';

export const WeeklySummariesPage: React.FC = () => {
  const [offset, setOffset] = useState(0);
  const limit = 12;
  const queryClient = useQueryClient();
  const markedRef = useRef<string | null>(null);
  const { data, isLoading, isError, refetch } = useQuery({
    queryKey: ['summaries', 'weekly', offset],
    queryFn: () => summariesService.listWeekly(limit, offset),
  });

  // Opening this page counts as reading the latest summary (spec-080): mark it
  // read so the dashboard's "summary is ready" briefing line clears. Only the
  // newest (first page, top item) is the one the briefing surfaces; guard so we
  // fire once per summary and never re-mark an already-read one. Depend on the
  // primitive id/read_at, not the `latest` object, so a query-data refetch that
  // returns an equal-but-new object reference doesn't re-run the effect.
  const latest = offset === 0 ? data?.items?.[0] : undefined;
  const latestId = latest?.public_id;
  const latestReadAt = latest?.read_at;
  useEffect(() => {
    if (!latestId || latestReadAt || markedRef.current === latestId) return;
    markedRef.current = latestId;
    void summariesService
      .markRead(latestId)
      .then(() => queryClient.invalidateQueries({ queryKey: queryKeys.dashboard.briefing() }))
      .catch(() => {
        // Non-critical: a failed mark-read just leaves the briefing line until
        // the freshness window lapses. Allow a retry on the next render.
        markedRef.current = null;
      });
  }, [latestId, latestReadAt, queryClient]);

  return (
    <PageShell>
      <PageHero
        title="Weekly Summaries"
        subtitle="A readable weekly view of productivity, spending, and portfolio movement."
      />

      {isLoading ? (
        <SkeletonList rows={4} />
      ) : isError ? (
        <ErrorBanner
          message="Failed to load weekly summaries. Please try again."
          onRetry={() => void refetch()}
        />
      ) : data?.items?.length ? (
        <>
          <div className="space-y-4">
            {data.items.map((item) => (
              <article
                key={item.public_id}
                className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 shadow-lg shadow-black/10"
              >
                <div className="mb-4 flex items-start justify-between gap-4">
                  <div>
                    <h2 className="font-semibold text-white">
                      Week of {formatDate(`${item.week_start}T00:00:00Z`, { fallback: 'N/A' })}
                    </h2>
                    <p className="mt-1 text-xs text-slate-500">
                      Generated {formatDateTime(item.generated_at, { fallback: 'N/A' })}
                    </p>
                  </div>
                </div>
                <div className="grid gap-3 lg:grid-cols-3">
                  <TodoCard summary={item.todo_summary} />
                  <SpendingCard summary={item.spending_summary} />
                  <InvestingCard summary={item.investing_summary} />
                </div>
                {(item.highlights?.flags?.length ?? 0) > 0 && (
                  <div className="mt-3 rounded-xl border border-cyan-800/60 bg-cyan-950/20 p-4">
                    <p className="text-xs font-semibold uppercase tracking-wider text-cyan-300">
                      Highlights
                    </p>
                    <ul className="mt-2 space-y-1 text-sm text-slate-200">
                      {item.highlights?.flags?.map((flag, index) => (
                        <li key={`${flag.type}-${index}`}>{flag.message}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </article>
            ))}
          </div>
          <div className="mt-5">
            <Pagination
              total={data.total}
              limit={data.limit}
              offset={data.offset}
              onPageChange={setOffset}
            />
          </div>
        </>
      ) : (
        <EmptyState
          icon={<CalendarDays className="h-6 w-6" />}
          title="No weekly summaries yet"
          description="Weekly summaries are automatically generated by backend jobs after activity is recorded for a full week."
        />
      )}
    </PageShell>
  );
};

const SummaryCard = ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) => (
  <div className="rounded-xl border border-slate-700 bg-slate-800/40 p-4">
    <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-400">{title}</p>
    <div className="space-y-2">{children}</div>
  </div>
);

const Metric = ({ label, value, valueClass = 'text-white' }: {
  label: string;
  value: React.ReactNode;
  valueClass?: string;
}) => (
  <div className="flex items-baseline justify-between gap-3 border-b border-slate-700/50 pb-2 last:border-0 last:pb-0">
    <span className="text-sm text-slate-400">{label}</span>
    <span className={`text-sm font-semibold ${valueClass}`}>{value}</span>
  </div>
);

const TodoCard = ({ summary }: { summary: WeeklySummary['todo_summary'] }) => (
  <SummaryCard title="Todo">
    <Metric label="Tasks created" value={summary?.tasks_created ?? 0} />
    <Metric label="Tasks completed" value={summary?.tasks_completed ?? 0} />
    {summary?.tasks_overdue != null && <Metric label="Tasks overdue" value={summary.tasks_overdue} />}
    {summary?.completion_rate_pct != null && (
      <Metric
        label="Completion rate"
        value={`${toNumber(summary.completion_rate_pct).toFixed(1)}%`}
      />
    )}
  </SummaryCard>
);

const SpendingCard = ({ summary }: { summary: WeeklySummary['spending_summary'] }) => {
  if (summary?.status !== 'complete' || !summary.currency || summary.has_multiple_currencies) {
    return (
      <SummaryCard title="Spending">
        <p className="text-sm text-amber-300">
          Combined spending totals are unavailable because this week contains multiple or
          unknown currencies.
        </p>
      </SummaryCard>
    );
  }
  return (
    <SummaryCard title="Spending">
      <Metric label="Recorded income" value={formatCurrency(summary.total_income, summary.currency)} />
      <Metric label="Recorded expense" value={formatCurrency(summary.total_expense, summary.currency)} />
      <Metric label="Net recorded amount" value={formatCurrency(summary.net, summary.currency)} />
      {summary.budget_utilization_pct != null && (
        <Metric label="Budget utilization" value={`${summary.budget_utilization_pct}%`} />
      )}
      <Metric label="Budgets breached" value={summary.budgets_breached ?? 0} />
      {(summary.top_categories ?? []).slice(0, 3).map((category) => (
        <Metric
          key={category.name}
          label={category.name}
          value={formatCurrency(category.amount, summary.currency)}
        />
      ))}
    </SummaryCard>
  );
};

const InvestingCard = ({ summary }: { summary: WeeklySummary['investing_summary'] }) => {
  if (summary?.status !== 'complete' || !summary?.currency) {
    return (
      <SummaryCard title="Investing">
        <p className="text-sm text-amber-300">
          Weekly comparison unavailable because compatible start and end snapshots were not found.
        </p>
      </SummaryCard>
    );
  }

  const change = toNumber(summary.week_change);
  const changePct = toNumber(summary.week_change_pct);
  const changeSign = change > 0 ? '+' : '';
  const pctSign = changePct > 0 ? '+' : '';
  const movementClass = change > 0 ? 'text-emerald-300' : change < 0 ? 'text-rose-300' : 'text-slate-200';
  return (
    <SummaryCard title="Investing">
      <Metric label="Portfolio value" value={formatCurrency(summary.portfolio_value_end, summary.currency)} />
      <Metric label="Investment cash" value={formatCurrency(summary.cash_end, summary.currency)} />
      <Metric
        label="Weekly movement"
        value={changeSign + formatCurrency(change, summary.currency) + " (" + pctSign + changePct.toFixed(2) + "%)"}
        valueClass={movementClass}
      />
      <Metric
        label="Valuation dates"
        value={`${summary.start_snapshot_date ?? 'N/A'} → ${summary.end_snapshot_date ?? 'N/A'}`}
        valueClass="text-slate-300"
      />
    </SummaryCard>
  );
};
